### ISSUE TITLE
not an issue: feedback

### ISSUE THREAD

**Issue by sriramb12** [gglockner/teslajson#14]
hello Greg
Firstly, this is not an issue! Its more of understanding python constructors
thanks for sharing the example code. I am looking for a way to code a constructor which can be more modular. In your code, I see its a long function with quite a few things. How can I define some functions which constructor can call?
I tried calling other class methods but I am getting scope error (undefined)
such breakdown is more modular and maybe reusable elsewhere

thanks
Sriram

**Comment by gglockner** [comment]
Sorry, try posting your question on StackOverflow.
