### ISSUE TITLE
Parms

### ISSUE THREAD

**Issue by the-mace** [gglockner/teslajson#2]
Hi there, theres a small tweak needed to allow things like sunroof state to be passed through. I can commit the changes but I don't have access. Thanks for making this little library available.

Attached is the file with the changes if you want to preview.
[teslajson.py.zip](https://github.com/gglockner/teslajson/files/139287/teslajson.py.zip)

**Comment by gglockner** [comment]
Could you fork the repository, make your changes, and make a pull request? That would be much easier for me. Cheers, Greg.

**Comment by the-mace** [comment]
Done thanks. Not used to working on public repos so this is a new process for me.
