### ISSUE TITLE
command/share

### ISSUE THREAD

**Issue by MarlinMr** [gglockner/teslajson#28]
I simply cannot get the sharing of navigation to work. Neither sharing media for that matter. It always returns a 500 error code. Might be connected to https://github.com/gglockner/teslajson/issues/19

Code:

`import teslajson, time;
c = teslajson.Connection('youremail', 'yourpassword');
v = c.vehicles[0];
location = '59.9375206,10.9285069';
params =  {'type':'share_ext_content_raw','value':{'android.intent.extra.TEXT':location},'locale':'en-US','timestamp_ms':str(time.time())[:10]};
v.command('navigation_request',params):`

**Comment by gglockner** [comment]
First, the API endpoint is now [sharing](https://tesla-api.timdorr.com/vehicle/commands/sharing), not navigation request. Such is life with an undocumented API.

Anyway, the following works for me, navigating me to the Costco store in Issaquah, WA:

```
import teslajson
import time

c = teslajson.Connection('myemail', 'mypassword')
v=c.vehicles[0]
data = {
  "type": "share_ext_content_raw",
  "value[android.intent.extra.TEXT]": "1801 10th Ave NW, Issaquah WA 98027",
  "locale": "en-US",
  "timestamp_ms": int(time.time())
}

v.command('share', data)
```

**Comment by MarlinMr** [comment]
Thanks.
