### ISSUE TITLE
email specification gives me error.

### ISSUE THREAD

**Issue by ghost** [gglockner/teslajson#4]
Hi

I copied the sample odometer script and just calling as is, seems to give me an error as shown below. Any idea about how to fix it?

 File "./tesla.py", line 7, in <module>
    TESLA_EMAIL = os.environ['my@gmail.com']
  File "/usr/lib64/python2.7/UserDict.py", line 23, in **getitem**
    raise KeyError(key)
KeyError: 'my@gmail.com'

**Comment by the-mace** [comment]
Yes, that os.environ call is getting an environment variable for the email address. If you want to just set it directly (by changing the script as you did) just set it directly like:

TESLA_EMAIL = 'my@gmail.com'

I made it an environment variable so you didnt have to modify the script.

**Comment by gglockner** [comment]
Sorry, what sample odometer script?

**Comment by the-mace** [comment]
I think he's talking about my stuff from https://github.com/the-mace/evtools that uses teslajson.

**Comment by ghost** [comment]
Yes.. do you have a method to reach across proxy's?

**Comment by the-mace** [comment]
Not sure what you mean, all traffic from these scripts is outbound so proxy is irrelevant.

**Comment by gglockner** [comment]
It could be a proxy server running on his network. Anyway, this looks like an issue in evtools, not teslajson.
