### ISSUE TITLE
http error 408 timeout

### ISSUE THREAD

**Issue by rawmean** [gglockner/teslajson#8]
I get a lot of http 408 (timeout) errors when I try to do a `.get` (e.g., `charge_state = v.get('data_request/charge_state')`

Is there a timeout parameter that I should modify to avoid this?

**Comment by gglockner** [comment]
Did you try waking the vehicle by calling `Vehicle.wake_up()` ?

**Comment by rawmean** [comment]
Yes.  This is what I do (after connecting with token):

    v.wake_up()
    charge_state = v.get('data_request/charge_state')

It doesn't always timeout.  Sometimes it works.  I also tried putting a `sleep` between `wake_up` and `get`, but it didn't make a difference.  The `Connection(access_token=token)` finishes with no error.

**Comment by TaylorSMarks** [comment]
I'm getting the same thing using an interactive session... does this just not work with the Model 3?

**Comment by rawmean** [comment]
I don't think the problem is related to Model 3. I think it's related to the server side and not this repo

**Comment by TaylorSMarks** [comment]
I just had this work for the first time. Someone else suggested that I just try polling, so that's what I did. Instead of just making the data request once, I have a loop around a try/except, where the try returns whatever the data_request returns and where the exception handler just prints out "Try x of 21: <exception>" and then sleeps for 3 seconds, then if it exits the loop (rather than returning from the function in the try block), it raises the last handled exception.

Output:

    Try 1 of 21: HTTP Error 408: Request Timeout
    Try 2 of 21: HTTP Error 408: Request Timeout
    Try 3 of 21: HTTP Error 408: Request Timeout
    Try 4 of 21: HTTP Error 408: Request Timeout
    Try 5 of 21: HTTP Error 408: Request Timeout

    {u'user_charge_enable_request': None, u'time_to_full_charge': 0.0,
     u'charge_current_request': 32, u'charge_enable_request': True, u'charge_to_max_range': False,
     u'charger_phases': None, u'battery_heater_on': False, u'battery_range': 259.07, u'charger_power': 0,
     u'charge_limit_soc': 84, u'max_range_charge_counter': 0, u'charge_port_latch': u'Engaged',
     u'charger_actual_current': 0, u'scheduled_charging_pending': False,
     u'fast_charger_brand': u'<invalid>', u'fast_charger_type': u'<invalid>',
     u'usable_battery_level': 84, u'charge_limit_soc_std': 90, u'managed_charging_start_time': None,
     u'battery_level': 84, u'charge_energy_added': 22.4, u'charge_port_door_open': True,
     u'charger_pilot_current': 32, u'timestamp': 1526738632395L, u'not_enough_power_to_heat': None,
     u'charge_limit_soc_max': 100, u'ideal_battery_range': 259.07, u'managed_charging_active': False,
     u'conn_charge_cable': u'SAE', u'charging_state': u'Complete', u'fast_charger_present': False,
     u'trip_charging': False, u'managed_charging_user_canceled': False,
     u'scheduled_charging_start_time': None, u'est_battery_range': 0.0, u'charge_rate': 0.0,
     u'charger_voltage': 2, u'charge_current_request_max': 32,
     u'charge_miles_added_ideal': 94.5, u'charge_limit_soc_min': 50, u'charge_miles_added_rated': 94.5}

I wonder if maybe I just need to wait 15 seconds after the wake_up command returns before I actually try doing anything?

**Comment by jackc88** [comment]
I think this is related to the vehicle needing to "Wake Up" as @TaylorSMarks suspected.
If I properly wake with the native Tesla app, the problems go away until I return again later on.

**Comment by nigelboid** [comment]
Thats right. Unlike older models, all newer cars (S, X, 3) sleep and require a wake-up call. Something like this seems to work well:

 # Wake up specified vehicle
  def __wake_up(self, vehicle_index):
    headers= self.get_headers()
    request= self.get_url() + OWNERAPI_VERSION + REQUEST_VEHICLES \
      + '/' + str(self.get_vehicle_id(vehicle_index)) \
      + '/' + COMMAND_WAKE_UP
      
    awake= False
    attempt= 0
    while attempt < MAX_ATTEMPTS:
      attempt+= 1
      response= requests.post(request, headers= headers)
      time.sleep(ATTEMPT_RETRY_DELAY)
    
      if response.status_code == STATUS_CODE_OK:
        if response.json()[STATUS_RESPONSE][KEY_VEHICLE_ONLINE_STATE] == VALUE_STATE_ONLINE_ONLINE:
          awake= True
          self.vehicles[KEY_VEHICLES][vehicle_index][KEY_VEHICLE_ONLINE_STATE]= VALUE_STATE_ONLINE_ONLINE
          break

**Comment by ejsuncy** [comment]
~~this library's `_open` function calls `urllib`'s `open` function but doesn't specify the `timeout` parameter, which it should. I'll work on a PR.~~ Yeah, looks like a server-side issue, which makes sense, you don't want hundreds of thousands of connections all waiting for vehicles to wake up. IMO polling might be a good option.

**Comment by rz93594** [comment]
I run this loop after the wake command and it is seeming pretty reliable for me as of late.


while True:
     state
     time.sleep(2)
     veh = c.vehicles[0]
     status = veh.wake_up()
     state = status['response']['state']
     if state == 'online':
        print(state)
        break
 
note: cleanup for your own use...
